version: "3.9"

services:
  run:
    build: .
    image: "exercise-6"
    container_name: exercise-6_app
    working_dir: /app
    volumes:
      - .:/app
      - ./reports:/app/reports
      - ./data:/app/data
    command: python main.py
